/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "../../TS102894-2v131-CDD.asn"
 */

#ifndef	_PhoneNumber_H_
#define	_PhoneNumber_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NumericString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PhoneNumber */
typedef NumericString_t	 PhoneNumber_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PhoneNumber;
asn_struct_free_f PhoneNumber_free;
asn_struct_print_f PhoneNumber_print;
asn_constr_check_f PhoneNumber_constraint;
ber_type_decoder_f PhoneNumber_decode_ber;
der_type_encoder_f PhoneNumber_encode_der;
xer_type_decoder_f PhoneNumber_decode_xer;
xer_type_encoder_f PhoneNumber_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _PhoneNumber_H_ */
#include <asn_internal.h>
